// games/FindTheCupGame.tsx
import React, { useState, useEffect, useCallback } from 'react';
import { useLocalStorage } from '../../../hooks/useLocalStorage';
import { useAppContext } from '../../../context/AppContext';
import Button from '../../shared/Button';
import BeerIcon from '../../icons/BeerIcon';
import { ArrowLeftIcon } from '@heroicons/react/24/solid';

const CUP_COUNT = 3;
const WIN_POINTS = 25;
const MAX_PLAYS_PER_DAY = 3;

type GameState = 'intro' | 'hint' | 'shuffling' | 'playing' | 'result';
type Cup = { id: number; order: number };
type DailyPlays = { date: string; count: number };

const FindTheCupGame: React.FC<{ onBack: () => void }> = ({ onBack }) => {
  const { state, awardPoints } = useAppContext();
  const { currentUser, selectedBar } = state;
  const [dailyPlays, setDailyPlays] = useLocalStorage<DailyPlays>(`findTheCupPlays_${currentUser?.id}`, { date: '', count: 0 });
  
  const [playsLeft, setPlaysLeft] = useState(MAX_PLAYS_PER_DAY);
  const [gameState, setGameState] = useState<GameState>('intro');
  const [cups, setCups] = useState<Cup[]>(Array.from({ length: CUP_COUNT }, (_, i) => ({ id: i, order: i })));
  const [winningCup, setWinningCup] = useState(Math.floor(Math.random() * CUP_COUNT));
  const [chosenCup, setChosenCup] = useState<number | null>(null);

  const updatePlays = useCallback(() => {
    const today = new Date().toISOString().split('T')[0];
    if (dailyPlays.date === today) {
        setPlaysLeft(Math.max(0, MAX_PLAYS_PER_DAY - dailyPlays.count));
    } else {
        setDailyPlays({ date: today, count: 0 });
        setPlaysLeft(MAX_PLAYS_PER_DAY);
    }
  }, [dailyPlays, setDailyPlays]);

  useEffect(() => {
    updatePlays();
  }, [updatePlays]);

  const startGame = () => {
    if (playsLeft <= 0) return;
    setGameState('hint');
    setChosenCup(null);
    setCups(Array.from({ length: CUP_COUNT }, (_, i) => ({ id: i, order: i })));
    setWinningCup(Math.floor(Math.random() * CUP_COUNT));

    setTimeout(() => {
        setGameState('shuffling');
        let shuffleCount = 0;
        const interval = setInterval(() => {
            setCups(prevCups => {
                const newCups = [...prevCups];
                const i = Math.floor(Math.random() * CUP_COUNT);
                let j = Math.floor(Math.random() * CUP_COUNT);
                while(i === j) { j = Math.floor(Math.random() * CUP_COUNT); }
                [newCups[i].order, newCups[j].order] = [newCups[j].order, newCups[i].order];
                return newCups;
            });
            shuffleCount++;
            if (shuffleCount >= 10) {
                clearInterval(interval);
                setGameState('playing');
            }
        }, 250);
    }, 1500);
  };
  
  const handleCupClick = (cupId: number) => {
    if (gameState !== 'playing') return;
    setChosenCup(cupId);
    setGameState('result');
    
    const isWinner = cupId === winningCup;
    if (isWinner) {
        if (currentUser && selectedBar) {
          awardPoints(currentUser.id, WIN_POINTS, selectedBar.id, 'Prêmio Ache o Copo');
        }
    }
    
    const today = new Date().toISOString().split('T')[0];
    const newCount = dailyPlays.date === today ? dailyPlays.count + 1 : 1;
    setDailyPlays({ date: today, count: newCount });
    setPlaysLeft(prev => prev - 1);
  };
  
  const getGameStateMessage = () => {
    switch (gameState) {
      case 'intro':
        return `Você tem ${playsLeft} jogada(s) restante(s).`;
      case 'hint':
        return 'Olhe onde está a bola!';
      case 'shuffling':
        return 'Preste atenção...';
      case 'playing':
        return 'Onde está a bola?';
      case 'result':
        return chosenCup === winningCup ? `Você venceu! +${WIN_POINTS} pontos!` : 'Não foi dessa vez!';
      default: return '';
    }
  };

  if (playsLeft <= 0 && gameState === 'intro') {
    return (
      <div className="text-center p-4">
         <button onClick={onBack} className="absolute top-4 left-4 text-dark-text-secondary hover:text-white z-20">
            <ArrowLeftIcon className="w-6 h-6" />
        </button>
        <h2 className="text-xl font-bold mb-4">Você já jogou todas as suas chances hoje!</h2>
        <p className="text-dark-text-secondary mb-6">Volte amanhã para mais diversão.</p>
        <Button onClick={onBack} variant="secondary">Voltar para os Jogos</Button>
      </div>
    );
  }

  return (
    <div 
        className="flex flex-col items-center w-full p-4 rounded-lg overflow-hidden" 
        style={{ background: 'linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.transparenttextures.com/patterns/wood-pattern.png), #4a2c2a' }}
    >
        <button onClick={onBack} className="absolute top-4 left-4 text-dark-text-secondary hover:text-white z-20">
            <ArrowLeftIcon className="w-6 h-6" />
        </button>

        <div className="text-center mb-8">
            <h2 className="text-3xl font-bold text-brand-accent">Ache o Copo</h2>
            <p className="text-lg text-dark-text-secondary min-h-[28px] transition-opacity duration-300">{getGameStateMessage()}</p>
        </div>
        
        <div className={`cup-container w-full h-48 flex justify-center items-end relative ${gameState === 'shuffling' ? 'shuffling' : ''}`}>
            {cups.map((cup) => {
                const isWinner = cup.id === winningCup;
                const isChosen = cup.id === chosenCup;

                return (
                    <div
                        key={cup.id}
                        className={`cup-wrapper w-1/3 h-full flex justify-center items-center 
                          ${gameState === 'result' && isWinner ? 'is-winner' : ''}
                          ${gameState === 'result' && !isWinner && isChosen ? 'is-loser' : ''}
                          ${gameState === 'hint' && isWinner ? 'is-hint' : ''}`
                        }
                        style={{
                            left: `${(cup.order * 33.33)}%`,
                            transform: (gameState === 'result' && isChosen) ? 'translateY(-20px)' : 'none',
                            zIndex: (gameState === 'result' && isChosen) ? 10 : 1,
                        }}
                    >
                        <button
                            onClick={() => handleCupClick(cup.id)}
                            disabled={gameState !== 'playing'}
                            className="cup-button w-28 h-36"
                            aria-label={`Copo ${cup.id + 1}`}
                        >
                            <BeerIcon />
                        </button>
                        <div className="loser-marker">❌</div>
                    </div>
                );
            })}
        </div>
        
        <div className="mt-12 h-16">
            {gameState === 'intro' && (
                <Button onClick={startGame} variant="accent" className="animate-pulse-accent px-8 py-4 text-lg">Começar!</Button>
            )}
            {gameState === 'result' && (
                <div className="flex gap-4">
                    {playsLeft > 0 ? (
                        <Button onClick={startGame} variant="accent">Jogar Novamente</Button>
                    ) : (
                        <p className="text-yellow-400 font-bold self-center">Fim das jogadas por hoje!</p>
                    )}
                    <Button onClick={onBack} variant="secondary">Voltar</Button>
                </div>
            )}
        </div>
    </div>
  );
};

export default FindTheCupGame;

// src/find-the-cup-game.component.ts
import { Component, ChangeDetectionStrategy, signal, computed } from '@angular/core';

const CUP_COUNT = 3;
const WIN_POINTS = 25;
const MAX_PLAYS_PER_DAY = 3;

type GameState = 'intro' | 'hint' | 'shuffling' | 'playing' | 'result';
type Cup = { id: number; order: number };
type DailyPlays = { date: string; count: number };

@Component({
  selector: 'app-find-the-cup-game',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div 
        class="flex flex-col items-center w-full p-4 rounded-lg overflow-hidden" 
        style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.transparenttextures.com/patterns/wood-pattern.png), #4a2c2a">

        <div class="text-center mb-8 relative">
            <h2 class="text-3xl font-bold text-brand-accent text-yellow-400">Ache o Copo</h2>
            <p class="text-lg text-gray-300 min-h-[28px] transition-opacity duration-300">{{ gameStateMessage() }}</p>
        </div>
        
        <div class="cup-container w-full h-48 flex justify-center items-end relative">
            @for (cup of cups(); track cup.id) {
                <div
                    class="cup-wrapper"
                    [class.is-winner]="gameState() === 'result' && cup.id === winningCup()"
                    [class.is-loser]="gameState() === 'result' && cup.id !== winningCup() && cup.id === chosenCup()"
                    [class.is-hint]="gameState() === 'hint' && cup.id === winningCup()"
                    [style.left.%]="cup.order * 33.33"
                    [style.transform]="gameState() === 'result' && cup.id === chosenCup() ? 'translateY(-20px)' : 'none'"
                    [style.z-index]="gameState() === 'result' && cup.id === chosenCup() ? 10 : 1"
                >
                    <button
                        (click)="handleCupClick(cup.id)"
                        [disabled]="gameState() !== 'playing'"
                        class="cup-button"
                        [attr.aria-label]="'Copo ' + (cup.id + 1)"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" class="w-full h-full" viewBox="0 0 100 125" fill="#a16207">
                            <path d="M15,5 H85 L75,110 H25 L15,5 Z" stroke="#663300" stroke-width="3" />
                            <path d="M15,5 Q50,20,85,5" fill="none" stroke="#663300" stroke-width="2" />
                            <ellipse cx="50" cy="110" rx="25" ry="5" fill="#663300" />
                        </svg>
                    </button>
                    <div class="ball"></div>
                    <div class="loser-marker">❌</div>
                </div>
            }
        </div>
        
        <div class="mt-12 h-16">
            @if (gameState() === 'intro' && playsLeft() > 0) {
                <button (click)="startGame()" class="bg-yellow-400 hover:bg-yellow-300 text-gray-900 font-bold py-3 px-8 rounded-full text-lg transition-transform duration-300 transform hover:scale-105 animate-pulse">Começar!</button>
            }
            @if (gameState() === 'result') {
                <div class="flex gap-4">
                    @if (playsLeft() > 0) {
                        <button (click)="startGame()" class="bg-yellow-400 hover:bg-yellow-300 text-gray-900 font-bold py-2 px-6 rounded-full">Jogar Novamente</button>
                    } @else {
                        <p class="text-yellow-400 font-bold self-center">Fim das jogadas por hoje!</p>
                    }
                </div>
            }
            @if (playsLeft() <= 0 && gameState() === 'intro') {
                <div class="text-center p-4">
                    <h2 class="text-xl font-bold mb-4 text-yellow-400">Você já jogou todas as suas chances hoje!</h2>
                    <p class="text-gray-300">Volte amanhã para mais diversão.</p>
                </div>
            }
        </div>
    </div>
  `,
  styles: [`
    .cup-container {
      perspective: 800px;
    }
    .cup-wrapper {
      position: absolute;
      width: 33.33%;
      height: 100%;
      display: flex;
      justify-content: center;
      align-items: center;
      transition: left 0.25s ease-in-out, transform 0.3s ease-in-out;
      transform-style: preserve-3d;
    }
    .cup-button {
      width: 7rem; /* w-28 */
      height: 9rem; /* h-36 */
      transition: transform 0.3s;
      cursor: pointer;
    }
    .cup-button:hover:not(:disabled) {
      transform: translateY(-10px) scale(1.05);
    }
    .ball, .loser-marker {
      position: absolute;
      opacity: 0;
      transition: opacity 0.3s ease-in-out, transform 0.3s ease-in-out;
      pointer-events: none;
    }
    .ball {
      width: 30px;
      height: 30px;
      background-color: #f59e0b; /* amber-500 */
      border-radius: 50%;
      bottom: -15px;
      box-shadow: 0 0 10px #f59e0b;
    }
    .loser-marker {
      font-size: 3rem;
      bottom: 2rem;
    }
    .is-hint {
      transform: translateY(-40px);
    }
    .is-hint .ball {
      opacity: 1;
    }
    .is-winner {
      transform: translateY(-40px);
    }
    .is-winner .ball {
      opacity: 1;
    }
    .is-loser .loser-marker {
      opacity: 1;
    }
  `]
})
export class FindTheCupGameComponent {
  gameState = signal<GameState>('intro');
  cups = signal<Cup[]>(Array.from({ length: CUP_COUNT }, (_, i) => ({ id: i, order: i })));
  winningCup = signal(0);
  chosenCup = signal<number | null>(null);
  playsLeft = signal(MAX_PLAYS_PER_DAY);
  
  private dailyPlaysStorageKey = 'findTheCupPlays_demo';

  constructor() {
    this.updatePlays();
  }

  gameStateMessage = computed(() => {
    switch (this.gameState()) {
      case 'intro': return `Você tem ${this.playsLeft()} jogada(s) restante(s).`;
      case 'hint': return 'Olhe onde está a bola!';
      case 'shuffling': return 'Preste atenção...';
      case 'playing': return 'Onde está a bola?';
      case 'result': return this.chosenCup() === this.winningCup() ? `Você venceu! +${WIN_POINTS} pontos!` : 'Não foi dessa vez!';
      default: return '';
    }
  });

  private updatePlays() {
    const today = new Date().toISOString().split('T')[0];
    const storedData = localStorage.getItem(this.dailyPlaysStorageKey);
    let dailyPlays: DailyPlays = { date: '', count: 0 };
    if (storedData) {
        dailyPlays = JSON.parse(storedData);
    }

    if (dailyPlays.date === today) {
        this.playsLeft.set(Math.max(0, MAX_PLAYS_PER_DAY - dailyPlays.count));
    } else {
        localStorage.setItem(this.dailyPlaysStorageKey, JSON.stringify({ date: today, count: 0 }));
        this.playsLeft.set(MAX_PLAYS_PER_DAY);
    }
  }

  startGame() {
    if (this.playsLeft() <= 0) return;
    this.gameState.set('hint');
    this.chosenCup.set(null);
    this.cups.set(Array.from({ length: CUP_COUNT }, (_, i) => ({ id: i, order: i })));
    this.winningCup.set(Math.floor(Math.random() * CUP_COUNT));

    setTimeout(() => {
        this.gameState.set('shuffling');
        let shuffleCount = 0;
        const interval = setInterval(() => {
            this.cups.update(prevCups => {
                const newCups = [...prevCups];
                const i = Math.floor(Math.random() * CUP_COUNT);
                let j = Math.floor(Math.random() * CUP_COUNT);
                while(i === j) { j = Math.floor(Math.random() * CUP_COUNT); }
                [newCups[i].order, newCups[j].order] = [newCups[j].order, newCups[i].order];
                return newCups;
            });
            shuffleCount++;
            if (shuffleCount >= 10) {
                clearInterval(interval);
                this.gameState.set('playing');
            }
        }, 250);
    }, 1500);
  }
  
  handleCupClick(cupId: number) {
    if (this.gameState() !== 'playing') return;
    this.chosenCup.set(cupId);
    this.gameState.set('result');
    
    // In a real app, this would be a service call.
    // For the demo, we just show a message.
    if (cupId === this.winningCup()) {
        console.log(`User won ${WIN_POINTS} points.`);
    }
    
    const today = new Date().toISOString().split('T')[0];
    const storedData = localStorage.getItem(this.dailyPlaysStorageKey);
    let dailyPlays: DailyPlays = { date: '', count: 0 };
    if (storedData) dailyPlays = JSON.parse(storedData);

    const newCount = dailyPlays.date === today ? dailyPlays.count + 1 : 1;
    localStorage.setItem(this.dailyPlaysStorageKey, JSON.stringify({ date: today, count: newCount }));
    this.playsLeft.update(p => p - 1);
  }
}
