// games/TicTacToeGame.tsx
import React, { useState, useEffect } from 'react';
import { useAppContext } from '../../../context/AppContext';
import Button from '../../shared/Button';
import { ArrowLeftIcon } from '@heroicons/react/24/solid';
import { toast } from 'react-hot-toast';

const PLAYER = 'X';
const AI = 'O';

// Helper function to calculate the winner
const calculateWinner = (squares: (string | null)[]) => {
  const lines = [
    [0, 1, 2], [3, 4, 5], [6, 7, 8], // rows
    [0, 3, 6], [1, 4, 7], [2, 5, 8], // columns
    [0, 4, 8], [2, 4, 6]             // diagonals
  ];
  for (let i = 0; i < lines.length; i++) {
    const [a, b, c] = lines[i];
    if (squares[a] && squares[a] === squares[b] && squares[a] === squares[c]) {
      return { winner: squares[a], line: lines[i] };
    }
  }
  if (squares.every(square => square)) {
    return { winner: 'T', line: null }; // T for Tie
  }
  return null;
};

const TicTacToeGame: React.FC<{ onBack: () => void }> = ({ onBack }) => {
  const { state, awardPoints } = useAppContext();
  const { currentUser, selectedBar } = state;

  const [board, setBoard] = useState(Array(9).fill(null));
  const [playerIsNext, setPlayerIsNext] = useState(true);
  const [winnerInfo, setWinnerInfo] = useState<{ winner: string; line: number[] | null } | null>(null);
  const [scores, setScores] = useState({ player: 0, ai: 0 });
  const [gameEnded, setGameEnded] = useState(false);

  const resetBoard = () => {
    setBoard(Array(9).fill(null));
    setPlayerIsNext(true);
    setWinnerInfo(null);
    setGameEnded(false);
  };

  const handlePlay = (index: number) => {
    if (winnerInfo || board[index] || !playerIsNext) {
      return;
    }
    const newBoard = board.slice();
    newBoard[index] = PLAYER;
    setBoard(newBoard);
    setPlayerIsNext(false);
  };
  
  // AI Logic
  useEffect(() => {
    const winner = calculateWinner(board);
    if (winner) {
      if (!gameEnded) { // Prevent multiple score updates
        setWinnerInfo(winner);
        if (winner.winner === PLAYER) {
          setScores(s => ({ ...s, player: s.player + 1 }));
          if (currentUser && selectedBar) {
            awardPoints(currentUser.id, 15, selectedBar.id, 'Vitória no Jogo da Velha');
            toast.success('+15 pontos pela vitória!');
          }
        } else if (winner.winner === AI) {
          setScores(s => ({ ...s, ai: s.ai + 1 }));
        }
        setGameEnded(true);
      }
      return;
    }

    if (!playerIsNext && !winner) {
      const timeout = setTimeout(() => {
        const bestMove = findBestMove(board);
        if (bestMove !== -1) {
          const newBoard = board.slice();
          newBoard[bestMove] = AI;
          setBoard(newBoard);
          setPlayerIsNext(true);
        }
      }, 500); // AI "thinks" for a moment
      return () => clearTimeout(timeout);
    }
  }, [board, playerIsNext, gameEnded]);

  const findBestMove = (currentBoard: (string|null)[]) => {
    // 1. Check if AI can win
    for (let i = 0; i < 9; i++) {
        if (!currentBoard[i]) {
            const tempBoard = currentBoard.slice();
            tempBoard[i] = AI;
            if (calculateWinner(tempBoard)?.winner === AI) return i;
        }
    }
    // 2. Check if player can win and block
    for (let i = 0; i < 9; i++) {
        if (!currentBoard[i]) {
            const tempBoard = currentBoard.slice();
            tempBoard[i] = PLAYER;
            if (calculateWinner(tempBoard)?.winner === PLAYER) return i;
        }
    }
    // 3. Take center if available
    if (!currentBoard[4]) return 4;
    // 4. Take a random corner
    const corners = [0, 2, 6, 8].filter(i => !currentBoard[i]);
    if (corners.length > 0) return corners[Math.floor(Math.random() * corners.length)];
    // 5. Take any available spot
    const emptySpots = currentBoard.map((val, idx) => val === null ? idx : null).filter(val => val !== null);
    return emptySpots[Math.floor(Math.random() * emptySpots.length)];
  }

  const getStatusMessage = () => {
    if (winnerInfo) {
      if (winnerInfo.winner === 'T') return 'Empate!';
      return winnerInfo.winner === PLAYER ? 'Você Venceu!' : 'A IA Venceu!';
    }
    return playerIsNext ? 'Sua vez de jogar' : 'IA está pensando...';
  };

  return (
    <div className="flex flex-col items-center w-full p-4">
      <button onClick={onBack} className="absolute top-4 left-4 text-dark-text-secondary hover:text-white">
        <ArrowLeftIcon className="w-6 h-6" />
      </button>
      <h2 className="text-3xl font-bold text-brand-accent mb-2">Jogo da Velha</h2>
      
      <div className="flex justify-around w-full max-w-xs my-4 text-lg">
        <div className="text-center">
            <div className="font-bold text-emerald-300">Você (X)</div>
            <div className="text-2xl font-black">{scores.player}</div>
        </div>
        <div className="text-center">
            <div className="font-bold text-red-300">IA (O)</div>
            <div className="text-2xl font-black">{scores.ai}</div>
        </div>
      </div>
      
      <div className="w-full max-w-xs aspect-square tic-tac-toe-board">
        {board.map((value, index) => (
          <button
            key={index}
            onClick={() => handlePlay(index)}
            disabled={!!value || !!winnerInfo}
            className={`tic-tac-toe-cell 
              ${value === 'X' ? 'x' : ''} 
              ${value === 'O' ? 'o' : ''}
              ${winnerInfo?.line?.includes(index) ? 'winner' : ''}
            `}
            aria-label={`Posição ${index + 1}`}
          />
        ))}
      </div>

      <div className="mt-6 text-center h-16 flex flex-col justify-center">
        <p className="text-xl font-semibold min-h-[28px]">{getStatusMessage()}</p>
        {winnerInfo && (
            <Button onClick={resetBoard} variant="accent" className="mt-4 px-6 py-2">
                Jogar Novamente
            </Button>
        )}
      </div>
    </div>
  );
};

export default TicTacToeGame;

// src/tic-tac-toe-game.component.ts
import { Component, ChangeDetectionStrategy, signal, computed, effect } from '@angular/core';

const PLAYER = 'X';
const AI = 'O';

function calculateWinner(squares: (string | null)[]) {
  const lines = [
    [0, 1, 2], [3, 4, 5], [6, 7, 8],
    [0, 3, 6], [1, 4, 7], [2, 5, 8],
    [0, 4, 8], [2, 4, 6]
  ];
  for (let i = 0; i < lines.length; i++) {
    const [a, b, c] = lines[i];
    if (squares[a] && squares[a] === squares[b] && squares[a] === squares[c]) {
      return { winner: squares[a], line: lines[i] };
    }
  }
  if (squares.every(square => square)) {
    return { winner: 'T', line: null }; // T for Tie
  }
  return null;
}

@Component({
  selector: 'app-tic-tac-toe-game',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="flex flex-col items-center w-full p-4">
      <h2 class="text-3xl font-bold text-yellow-400 mb-2">Jogo da Velha</h2>
      
      <div class="flex justify-around w-full max-w-xs my-4 text-lg">
        <div class="text-center">
            <div class="font-bold text-emerald-300">Você (X)</div>
            <div class="text-2xl font-black">{{ scores().player }}</div>
        </div>
        <div class="text-center">
            <div class="font-bold text-red-300">IA (O)</div>
            <div class="text-2xl font-black">{{ scores().ai }}</div>
        </div>
      </div>
      
      <div class="w-full max-w-xs aspect-square tic-tac-toe-board">
        @for(value of board(); track $index) {
          <button
            (click)="handlePlay($index)"
            [disabled]="!!value || !!winnerInfo()"
            class="tic-tac-toe-cell"
            [class.x]="value === 'X'"
            [class.o]="value === 'O'"
            [class.winner]="winnerInfo()?.line?.includes($index)"
            [attr.aria-label]="'Posição ' + ($index + 1)"
          ></button>
        }
      </div>

      <div class="mt-6 text-center h-16 flex flex-col justify-center">
        <p class="text-xl font-semibold min-h-[28px] text-gray-300">{{ statusMessage() }}</p>
        @if (winnerInfo()) {
            <button (click)="resetBoard()" class="mt-4 px-6 py-2 bg-yellow-400 hover:bg-yellow-300 text-gray-900 font-bold rounded-full">
                Jogar Novamente
            </button>
        }
      </div>
    </div>
  `,
  styles: [`
    .tic-tac-toe-board {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 10px;
    }
    .tic-tac-toe-cell {
      width: 100%;
      aspect-ratio: 1 / 1;
      position: relative;
      background-color: #374151; /* bg-gray-700 */
      border-radius: 8px;
      cursor: pointer;
      transition: background-color 0.2s;
    }
    .tic-tac-toe-cell:hover:not(:disabled) {
      background-color: #4b5563; /* bg-gray-600 */
    }
    .tic-tac-toe-cell:disabled {
      cursor: not-allowed;
    }
    .tic-tac-toe-cell::before,
    .tic-tac-toe-cell::after {
      content: '';
      position: absolute;
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%) scale(0);
      background-color: white;
      transition: transform 0.3s ease;
    }
    .tic-tac-toe-cell.x::before, .tic-tac-toe-cell.x::after {
      width: 80%;
      height: 15%;
      border-radius: 10px;
      background-color: #34d399; /* emerald-400 */
      transform: translate(-50%, -50%) scale(1) rotate(45deg);
    }
    .tic-tac-toe-cell.x::after {
      transform: translate(-50%, -50%) scale(1) rotate(-45deg);
    }
    .tic-tac-toe-cell.o::before {
      width: 70%;
      height: 70%;
      border-radius: 50%;
      border: 12px solid #f87171; /* red-400 */
      background-color: transparent;
      transform: translate(-50%, -50%) scale(1);
    }
    .tic-tac-toe-cell.winner {
      background-color: #ca8a04; /* yellow-600 */
    }
  `]
})
export class TicTacToeGameComponent {
  board = signal<(string | null)[]> (Array(9).fill(null));
  playerIsNext = signal(true);
  scores = signal({ player: 0, ai: 0 });

  winnerInfo = computed(() => calculateWinner(this.board()));
  
  statusMessage = computed(() => {
    const winner = this.winnerInfo();
    if (winner) {
      if (winner.winner === 'T') return 'Empate!';
      return winner.winner === PLAYER ? 'Você Venceu!' : 'A IA Venceu!';
    }
    return this.playerIsNext() ? 'Sua vez de jogar' : 'IA está pensando...';
  });

  constructor() {
    effect((onCleanup) => {
      const winner = this.winnerInfo();
      const isNext = this.playerIsNext();
      
      if(winner) {
          if (winner.winner === PLAYER) {
              this.scores.update(s => ({...s, player: s.player + 1}));
          } else if (winner.winner === AI) {
              this.scores.update(s => ({...s, ai: s.ai + 1}));
          }
          return;
      }

      if (!isNext) {
        const timeout = setTimeout(() => {
          this.makeAiMove();
        }, 600);
        onCleanup(() => clearTimeout(timeout));
      }
    }, { allowSignalWrites: true });
  }

  resetBoard() {
    this.board.set(Array(9).fill(null));
    this.playerIsNext.set(true);
  }

  handlePlay(index: number) {
    if (this.winnerInfo() || this.board()[index] || !this.playerIsNext()) {
      return;
    }
    this.board.update(b => {
      const newBoard = b.slice();
      newBoard[index] = PLAYER;
      return newBoard;
    });
    this.playerIsNext.set(false);
  }
  
  private makeAiMove() {
      const currentBoard = this.board();
      // 1. Check if AI can win
      for (let i = 0; i < 9; i++) {
        if (!currentBoard[i]) {
          const tempBoard = currentBoard.slice();
          tempBoard[i] = AI;
          if (calculateWinner(tempBoard)?.winner === AI) {
            this.updateBoardForAI(i);
            return;
          }
        }
      }
      // 2. Check if player can win and block
      for (let i = 0; i < 9; i++) {
        if (!currentBoard[i]) {
          const tempBoard = currentBoard.slice();
          tempBoard[i] = PLAYER;
          if (calculateWinner(tempBoard)?.winner === PLAYER) {
            this.updateBoardForAI(i);
            return;
          }
        }
      }
      // 3. Take center if available
      if (!currentBoard[4]) {
          this.updateBoardForAI(4);
          return;
      }
      // 4. Take a random corner
      const corners = [0, 2, 6, 8].filter(i => !currentBoard[i]);
      if (corners.length > 0) {
          this.updateBoardForAI(corners[Math.floor(Math.random() * corners.length)]);
          return;
      }
      // 5. Take any available spot
      const emptySpots = currentBoard.map((val, idx) => val === null ? idx : null).filter((val): val is number => val !== null);
      if(emptySpots.length > 0) {
        this.updateBoardForAI(emptySpots[Math.floor(Math.random() * emptySpots.length)]);
      }
  }

  private updateBoardForAI(index: number) {
      this.board.update(b => {
          const newBoard = b.slice();
          newBoard[index] = AI;
          return newBoard;
      });
      this.playerIsNext.set(true);
  }
}
